### PR TITLE
Implement std::iter::{Sum, Product}

### LINKED ISSUE #3: Implement std::iter::{Sum,Product}
(copying from rust-num/num#233, here for `Complex` only)

The [Sum](https://doc.rust-lang.org/std/iter/trait.Sum.html) and [Product](https://doc.rust-lang.org/std/iter/trait.Product.html) traits are stable in 1.12.0, so we could implement them for our types.

(But we consider it a breaking change to increase the required rustc.)

### PR DESCRIPTION
**Pull request by termoshtt**
Resolve #3 

- Implement `Sum<Complex<T>>` and `Sum<&Complex<T>>` using `Zero` + `AddAssign`
- Implement `Product<Complex<T>>` and `Product<&Complex<T>>` using `One` + `MulAssign`

`Num` and `NumAssign` are used for type constraint.

### CODE REVIEW

**Comment by termoshtt** [comment]
```
error: no associated item named `new` found for type `std::collections::hash_map::DefaultHasher` in the current scope
    --> src/lib.rs:1162:22
     |
1162 |     let mut hasher = <RandomState as BuildHasher>::Hasher::new();
     |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I met this error with 1.12.0. I will use 1.14.0 like #7

**Comment by cuviper** [comment]
Thanks - I'll need to hold this PR until I'm ready to make breaking changes.

**Comment by termoshtt** [comment]
I see the [num-complex 0.2 milestone](https://github.com/rust-num/num-complex/milestone/1), where these two issues are listed. Is there another issue to be included in num-complex 0.2 ?

**Comment by cuviper** [comment]
Maybe also #6 for `no_std`, after rust-num/num-traits#16.

**Comment by termoshtt** [comment]
I guess the `no_std` feature of num-traits will take a long time...
IMHO, we bump up version to 0.2 with the current two issues, and postpone the `no_std` feature to 0.3. What do you think about it?

**Comment by cuviper** [comment]
I'd rather work it out and bump only once in a long while.

**Comment by cuviper** [comment]
Rebased, then I made it use folds instead.  Thanks for the PR!

bors r+

**Pull request merged**
